on: pull_request
name: Fluent-linter
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: running_linter
        uses: calyptia/fluent-linter-action@gg/using-new-sdk
        with:
          CALYPTIA_API_KEY: ${{ secrets.CALYPTIA_API_KEY }}
          CONFIG_LOCATION_GLOB: '__fixtures__/configurations/*.conf'
